import os
import json
from pathlib import Path
import argparse
import openai

from kgcompass.config import BAILIAN_API_KEY, DEEPSEEK_BASE_URL, REVIEW_MODEL_NAME, TEMPERATURE, TOP_P

def _get_client() -> openai.OpenAI:
    if not BAILIAN_API_KEY:
        raise ValueError("GEMINI_API_KEY is not set (used as BAILIAN_API_KEY in config.py)")
    return openai.OpenAI(api_key=BAILIAN_API_KEY, base_url=DEEPSEEK_BASE_URL)


def discover_instances(tests_dir: str | Path = "tests", run_suffix: str = "_gemini") -> list[str]:
    """Discover instance_ids from run directories like `tests/<instance_id>_gemini/`."""
    tests_path = Path(tests_dir)
    if not tests_path.exists():
        return []

    instance_ids: list[str] = []
    for p in tests_path.iterdir():
        if not p.is_dir():
            continue
        name = p.name
        if not name.endswith(run_suffix):
            continue
        instance_id = name[: -len(run_suffix)]
        if instance_id:
            instance_ids.append(instance_id)
    return sorted(set(instance_ids))


def pick_latest_instance(tests_dir: str | Path = "tests", run_suffix: str = "_gemini") -> str | None:
    """Pick the most recently modified run directory and return its instance_id."""
    tests_path = Path(tests_dir)
    candidates: list[Path] = []
    if tests_path.exists():
        for p in tests_path.iterdir():
            if p.is_dir() and p.name.endswith(run_suffix):
                candidates.append(p)
    if not candidates:
        return None
    latest = max(candidates, key=lambda p: p.stat().st_mtime)
    return latest.name[: -len(run_suffix)] or None

def load_artifacts(instance_id):
    """Loads the JSON (KG context) and Diff/Patch files generated by KGCompass."""
    base_dir = Path(f"tests/{instance_id}_gemini")
    
    # 1. Load JSON file
    json_path = Path(f"{instance_id}.json") 
    if not json_path.exists():
        json_path = base_dir / "final_locations" / f"{instance_id}.json"
        
    with open(json_path, 'r', encoding='utf-8') as f:
        kg_data = json.load(f)
        
    # 2. Try to load .diff file first
    diff_dir = base_dir / "patches" / "diff_patches"
    diff_content = ""
    
    if diff_dir.exists():
        for file in diff_dir.iterdir():
            if file.suffix == '.diff':
                with open(file, 'r', encoding='utf-8') as f:
                    diff_content = f.read()
                break
                
    # 3. FALLBACK: If .diff is missing or empty, load the .patch file instead 🌟
    if not diff_content.strip():
        patch_file = base_dir / "patches" / f"{instance_id}.patch"
        if patch_file.exists():
            print("Note: .diff file not found. Falling back to .patch file for review...")
            with open(patch_file, 'r', encoding='utf-8') as f:
                diff_content = f.read()
                
    return kg_data, diff_content
def build_prompt(kg_data, diff_content):
    # 1. Extract the issue description
    issue_desc = ""
    for issue in kg_data.get("related_entities", {}).get("issues", []):
        if issue.get("type") == "issue":
            issue_desc = issue.get("content", "")
            break

    # 2. Extract the top 3 most similar methods
    impact_methods = []
    methods = kg_data.get("related_entities", {}).get("methods", [])
    
    # Get the top 10 most similar methods
    for method in methods[:10]:
        signature = method.get("signature", "Unknown Signature")
        docstring = method.get("doc_string", "").strip()
        
        if docstring:
            impact_methods.append(f"- `{signature}`\n  (Role: {docstring})")
        else:
            impact_methods.append(f"- `{signature}`")
            
    impact_context = "\n\n".join(impact_methods)

    # 3. Build the prompt

    
    prompt = f"""
<issue_description>
# Original Bug Report
Consider the following bug report:
{issue_desc}
</issue_description>

<kg_impact_context>
# Knowledge Graph Related Methods (Impact Analysis)
The following system components have been identified by our Knowledge Graph as potentially affected by this patch. 
Use these to understand the broader impact and potential side-effects of the proposed changes:

{impact_context}
</kg_impact_context>

<proposed_patch>
# Proposed Patch (Git Diff)
Below is the proposed fix for the issue:

{diff_content}
</proposed_patch>

<instructions>
# Task Instructions

## Overview
You are a Senior Software Engineer and an expert Code Reviewer.
Your task is to review the proposed patch (`<proposed_patch>`) based on the original bug report (`<issue_description>`) and the impact area identified by the Knowledge Graph (`<kg_impact_context>`).

## Evaluation Criteria
Please analyze the patch based on the following specific criteria:

1. **Correctness:** Does this patch accurately solve the root cause of the bug described in the report?
2. **Side-effects:** Considering the 'Impact Area' (KG Context), is there any risk of breaking existing functionalities or causing regressions in related methods?
3. **Code Quality:** Does the patch follow standard software engineering best practices? Are there any performance, memory, or edge-case concerns?

## Output Requirements

<IMPORTANT>
Your response MUST explicitly state your final verdict as either **[Approve]** or **[Request Changes]** based on your analysis.
</IMPORTANT>

- Format your response in clean, highly readable Markdown.
- Structure your review using the evaluation criteria listed above as headings.
- Provide a brief summary of your reasoning for the final verdict.
</instructions>
"""
    return prompt

def run_code_review(instance_id):
    print(f"Starting code review for {instance_id}...")
    
    # 1. Load the data
    try:
        kg_data, diff_content = load_artifacts(instance_id)
        if not diff_content:
            print("Diff file not found.")
            return
    except Exception as e:
        print(f"File loading error: {e}")
        return
        
    # 2. Build the prompt
    prompt = build_prompt(kg_data, diff_content)
    
    # 3. Call the API
    print("Calling review model:", REVIEW_MODEL_NAME, "\n")
    try:
        client = _get_client()
        response = client.chat.completions.create(
            model=REVIEW_MODEL_NAME,
            messages=[{"role": "user", "content": prompt}],
            temperature=TEMPERATURE,
            top_p=TOP_P,
        )
        if not response.choices:
            print("LLM API returned no choices.")
            return
        review_text = response.choices[0].message.content or ""
    except Exception as e:
        print(f"An error occurred while calling the LLM API: {e}")
        return
    
    # 4. Output and save the result
    print("="*60)
    print("[Code Review Report]")
    print("="*60)
    print(review_text)
    print("="*60)
    
    # Save the result to a Markdown file
    report_path = f"tests/{instance_id}_gemini/{instance_id}_review_report.md"
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(review_text)
    print(f"\nCode review report saved to: {report_path}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run patch review using KGCompass artifacts under tests/<instance>_gemini.")
    parser.add_argument(
        "--instance_id",
        type=str,
        action="append",
        help="Instance id to review. Can be provided multiple times. If omitted, runs all discovered instances.",
    )
    parser.add_argument("--tests_dir", type=str, default="tests", help="Directory that contains run artifacts (default: tests).")
    parser.add_argument("--list", action="store_true", help="List discovered instance ids and exit.")
    parser.add_argument("--all", action="store_true", help="Review all discovered instances.")
    args = parser.parse_args()

    instances = discover_instances(args.tests_dir)
    if args.list:
        for iid in instances:
            print(iid)
        raise SystemExit(0)

    if not instances:
        print(f"No run directories found under `{args.tests_dir}` matching `*_{'gemini'}`.")
        raise SystemExit(1)

    # Determine which instances to review
    selected: list[str]
    if args.all or not args.instance_id:
        selected = instances
    else:
        # Flatten any comma/space-separated values while keeping support for repeated flags.
        requested: list[str] = []
        for raw in args.instance_id:
            requested.extend([s for s in raw.replace(",", " ").split() if s])
        selected = requested

    # Run reviews sequentially
    for iid in selected:
        if iid not in instances:
            print(f"Skipping unknown instance_id (no matching directory under tests): {iid}")
            continue
        run_code_review(iid)